# Generated by Django 4.2 on 2025-01-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_group_quizzes_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('WRITING', 'Writing Question')], default='MCQ', max_length=10),
        ),
    ]
