# Generated by Django 4.2 on 2025-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_question_question_type_mcqanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit for the quiz in minutes.'),
        ),
    ]
