# Generated by Django 5.0.12 on 2025-03-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_quizzes_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingAnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(choices=[('CREATED', 'Created'), ('ANSWERED', 'Answered'), ('CHECKED', 'Checked')], default='CREATED', help_text='Status of the answer: CREATED, ANSWERED, or CHECKED.', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.teacher')),
                ('writing_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.writinganswer')),
            ],
        ),
    ]
