# Generated by Django 5.0.14 on 2025-05-17 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mcqquestion_notice_passage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in seconds for completing the passage', null=True),
        ),
        migrations.AlterField(
            model_name='mcqanswer',
            name='answer_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PassageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('score_percentage', models.FloatField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField()),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_submissions', to='api.passage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'passage')},
            },
        ),
    ]
