# Generated by Django 5.0.14 on 2025-05-19 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_passagesubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
