# Generated by Django 5.0.14 on 2025-05-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_writtenquestion_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passagesubmission',
            name='score_percentage',
        ),
        migrations.RemoveField(
            model_name='passagesubmission',
            name='total_questions',
        ),
        migrations.AlterField(
            model_name='passage',
            name='time_limit',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='writtenpassagesubmission',
            name='passage_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_passage_submission', to='api.passagesubmission'),
        ),
    ]
